<?xml version="1.0"?>

<!--
    niryo_one.urdf.xacro
    Copyright (C) 2019 Niryo
    All rights reserved.

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="niryo_one">
    <!-- Arguments -->
    <xacro:arg name="standalone" default="true" />
    <xacro:arg name="parent_link" default="world" />
    <xacro:arg name="pose_x" default="0.0" />
    <xacro:arg name="pose_y" default="0.0" />
    <xacro:arg name="pose_z" default="0.0" />
    <xacro:arg name="rotation_z" default="0.0" />

    <!-- Properties -->
    <xacro:property name="com_mainsupport_x" value="-0.00216" />
    <xacro:property name="com_mainsupport_z" value="0.02135" />
    <xacro:property name="com_mainsupport_y" value="-0.00204" />

    <xacro:property name="distance_origin_shoulder_z" value="0.103" />
    <xacro:property name="distance_shoulder_arm_z" value="0.080" />
    <xacro:property name="distance_arm_elbow_x" value="0.210" />
    <xacro:property name="distance_elbow_forearm_x" value="0.0415" />
    <xacro:property name="distance_elbow_forearm_y" value="0.030" />
    <xacro:property name="distance_forearm_wrist_z" value="0.180" />
    <xacro:property name="distance_wrist_hand_x" value="0.0164" />
    <xacro:property name="distance_wrist_hand_y" value="-0.0055" />
    <xacro:property name="distance_hand_tool" value="0.0073" />

    <xacro:property name="PI" value="3.14159265359" />

    <xacro:property name="limit_low_shoulder_rotation" value="-3.05433" />
    <xacro:property name="limit_up_shoulder_rotation" value="3.05433" />
    <xacro:property name="limit_low_arm_rotation" value="-1.91986" />
    <xacro:property name="limit_up_arm_rotation" value="0.640187" />
    <xacro:property name="limit_low_elbow_rotation" value="-1.397485" />
    <xacro:property name="limit_up_elbow_rotation" value="${PI/2}" />
    <xacro:property name="limit_low_forearm_rotation" value="-3.05433" />
    <xacro:property name="limit_up_forearm_rotation" value="3.05433" />
    <xacro:property name="limit_low_wrist_rotation" value="-1.74533" />
    <xacro:property name="limit_up_wrist_rotation" value="1.91986" />
    <xacro:property name="limit_low_hand_rotation" value="-2.57436" />
    <xacro:property name="limit_up_hand_rotation" value="2.57436" />
    <xacro:property name="limit_low_hand_rotation" value="-2.57436" />
    <xacro:property name="limit_up_hand_rotation" value="2.57436" />

    <!-- Includes -->
    <xacro:include filename="$(find niryo_one_description)/urdf/niryo_one_gazebo.urdf.xacro" />
    <xacro:include filename="$(find niryo_one_description)/urdf/niryo_one_transmission.urdf.xacro" />

    <!-- Links -->
    <xacro:if value="$(arg standalone)">
        <link name="world" />
    </xacro:if>

    <link name="base_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/base_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/base_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_origin_shoulder_z / 2}" rpy="0 0 0" />
            <mass value="1.2" />
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015" />
        </inertial>
    </link>

    <link name="shoulder_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/shoulder_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/shoulder_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_shoulder_arm_z / 2}" rpy="0 0 0" />
            <mass value="0.8" />
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015" />
        </inertial>
    </link>

    <link name="arm_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/arm_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/arm_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_arm_elbow_x / 2} 0.006 0.003" rpy="0 0 0" />
            <mass value="0.4" />
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015" />
        </inertial>
    </link>

    <link name="elbow_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/elbow_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/elbow_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_elbow_forearm_x / 2} ${distance_elbow_forearm_y / 2} 0" rpy="0 0 0" />
            <mass value="0.3" />
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015" />
        </inertial>
    </link>

    <link name="forearm_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/forearm_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/forearm_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_forearm_wrist_z / 2}" rpy="0 0 0" />
            <mass value="0.3" />
            <inertia ixx="0.0015" ixy="0.0" ixz="0.0" iyy="0.0015" iyz="0.0" izz="0.0015" />
        </inertial>
    </link>

    <link name="wrist_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/wrist_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/wrist_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${distance_wrist_hand_x / 2} ${distance_wrist_hand_y / 2} 0" rpy="0 0 0" />
            <mass value="0.15" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>
    </link>

    <link name="hand_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/hand_link.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/hand_link.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 ${distance_hand_tool / 2}" rpy="0 0 0" />
            <mass value="0.05" />
            <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
        </inertial>
    </link>

    <link name="mainsupport">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/collada/spoon_effector.dae" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://niryo_one_description/meshes/stl/spoon_effector.stl" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="${com_mainsupport_x} ${com_mainsupport_y} ${com_mainsupport_z}" rpy="0 0 0" />
            <mass value="0.01306" />
            <!--<inertia ixx="4.94888021667e-06" ixy="0.0" ixz="0.0" iyy="4.27188246667e-06" iyz="0.0" izz="5.00673601667e-06"/>-->
            <inertia ixx="4.94888021667e-03" ixy="0.0" ixz="0.0" iyy="4.27188246667e-03" iyz="0.0" izz="5.00673601667e-03" />
        </inertial>
    </link>

    <link name="tool_link"></link>

    <!--Joints -->
    <joint name="joint_base" type="fixed">
        <parent link="$(arg parent_link)" />
        <child link="base_link" />
        <origin xyz="$(arg pose_x) $(arg pose_y) $(arg pose_z)" rpy="0 0 $(arg rotation_z)" />
    </joint>

    <joint name="joint_1" type="revolute">
        <parent link="base_link" />
        <child link="shoulder_link" />
        <origin xyz="0 0 ${distance_origin_shoulder_z}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_shoulder_rotation}" upper="${limit_up_shoulder_rotation}" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="joint_2" type="revolute">
        <parent link="shoulder_link" />
        <child link="arm_link" />
        <origin xyz="0 0 ${distance_shoulder_arm_z}" rpy="${PI/2} ${-PI/2} 0" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_arm_rotation}" upper="${limit_up_arm_rotation}" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="joint_3" type="revolute">
        <parent link="arm_link" />
        <child link="elbow_link" />
        <origin xyz="${distance_arm_elbow_x} 0 0" rpy="0 0 ${-PI/2}" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_elbow_rotation}" upper="${limit_up_elbow_rotation}" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="joint_4" type="revolute">
        <parent link="elbow_link" />
        <child link="forearm_link" />
        <origin xyz="${distance_elbow_forearm_x} ${distance_elbow_forearm_y} 0" rpy="0 ${PI/2} 0" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_forearm_rotation}" upper="${limit_up_forearm_rotation}" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="joint_5" type="revolute">
        <parent link="forearm_link" />
        <child link="wrist_link" />
        <origin xyz="0 0 ${distance_forearm_wrist_z}" rpy="0 ${-PI/2} 0" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_wrist_rotation}" upper="${limit_up_wrist_rotation}" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="joint_6" type="revolute">
        <parent link="wrist_link" />
        <child link="hand_link" />
        <origin xyz="${distance_wrist_hand_x} ${distance_wrist_hand_y} 0" rpy="0 ${PI/2} 0" />
        <limit effort="100.0" velocity="3.0" lower="${limit_low_hand_rotation}" upper="${limit_up_hand_rotation}" />
        <axis xyz="0 0 1" />
        <dynamics damping="0.1" friction="0.0" />
    </joint>

    <joint name="tool_joint" type="fixed">
        <parent link="hand_link" />
        <child link="tool_link" />
        <origin xyz="0 0 ${distance_hand_tool}" rpy="0 0 0" />
    </joint>

    <joint name="mainsupport_joint" type="fixed">
        <parent link="tool_link" />
        <child link="mainsupport" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>


    <!-- Adding Kinect Depth Camera  -->
    <joint name="camera_joint" type="fixed">
        <axis xyz="0 1 0" />
        <!--<origin xyz="-0.101 0.274 0.257" rpy="-2.083 -0.176 -1.850" /> 1.5708-->
	<origin xyz="0 0.04 0.02" rpy="-1.5708 -1.5708 0" />
        <!--<parent link="base_link" />-->
	<parent link="tool_link" />
        <child link="camera_link" />
    </joint>

    <!-- Camera -->
    <link name="camera_link">
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.03 0.03" />
            </geometry>
        </collision>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.03 0.03" />
            </geometry>
            <material name="blue" />
        </visual>

        <inertial>
            <mass value="1e-5" />
            <origin xyz="0 0 0.0" rpy="0 0 0" />
            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
        </inertial>
    </link>

    <!-- Camera Adujustment (it's originally set to point in x, gotta rotate around y by 90) -->
    <joint name="camera_joint_fix" type="fixed">
        <axis xyz="0 1 0" />
        <!--<origin xyz="0.2 -0.3 0.2" rpy="0 -2.0 1.5" />-->
	<origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="camera_link" />
        <child link="camera_link_adjust" />
    </joint>

    <link name="camera_link_adjust"></link>

    <gazebo reference="camera_link_adjust">
        <sensor name="camera_link_adjustcamera" type="depth">
            <update_rate>20</update_rate>
            <camera>
                <horizontal_fov>1.047198</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
            </camera>
            <plugin name="depth_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>camera_ir</cameraName>
                <imageTopicName>/camera/color/image_raw</imageTopicName>
                <cameraInfoTopicName>/camera/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>/camera/depth/image_raw</depthImageTopicName>
                <depthImageInfoTopicName>/camera/depth/camera_info</depthImageInfoTopicName>
                <pointCloudTopicName>/camera/depth/points</pointCloudTopicName>
                <frameName>camera_link</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
            </plugin>
        </sensor>
    </gazebo>
</robot>
